version: '3'
services:
  registry:
    image: registry
    restart: always
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    labels:
      - traefik.enable=true
      - traefik.port=5000
      - traefik.frontend.rule=Host:registry.${SERVER_DOMAIN}
    volumes:
      - ${SETTINGS_PATH}/registry/data:/var/lib/registry
      - ${SETTINGS_PATH}/registry/auth:/auth
    networks:
      - core

networks:
  core:
    external: true
