version: '3'
services:
  template:
    container_name: template
    image: docker.fredriklowenhamn.se/template
    restart: always
    networks:
      - core
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:template.${SERVER_DOMAIN}
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - DB_HOST=rethinkdb

networks:
  core:
    external: true
