version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:1.7-alpine
    restart: always
    ports:
      - ${INTERNAL_PORT80}:80
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.${SERVER_DOMAIN}
    command: --web --logLevel=DEBUG --docker 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - core

  ptraefik:
    container_name: ptraefik
    image: public-traefik
    build: ./core-apps/traefik/
    restart: always
    ports:
      - ${PORT80}:80
      - ${PORT443}:443
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:ptraefik.${SERVER_DOMAIN}
    command: --web --logLevel=DEBUG --configfile=/toml/traefik-public.toml --docker.exposedbydefault=false
    volumes:
      - ${SETTINGS_PATH}/traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - core

  oauth2proxy:
    container_name: oauth2proxy
    image: oauth2proxy
    build: ./core-apps/oauth2proxy/
    command: --cookie-secure=false --upstream="http://traefik:80" --http-address="0.0.0.0:4180" --redirect-url="https://portal.${SERVER_DOMAIN}/oauth2/callback" --authenticated-emails-file=/auth/emails
    volumes:
      - ${SETTINGS_PATH}/oauth2proxy:/auth
    labels:
      - traefik.enable=false
    env_file: ./.env
    restart: always
    networks:
      - core

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ${SETTINGS_PATH}/portainer:/data
    command: --no-auth
    labels:
      - traefik.port=9000
      - traefik.frontend.rule=Host:portainer.${SERVER_DOMAIN}
    networks:
      - core

networks:
  core:
    external: true
