version: '3'
services:
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: always
    labels:
      - traefik.enable=false
    command: --interval 20 ${WATCHTOWER_TARGETS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG}:/config.json
    networks:
      - core

networks:
  core:
    external: true
