version: '3'
services:
  guacamole-mysql:
    container_name: guacamole-mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ${SETTINGS_PATH}/guacamole:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gurkburk
      - MYSQL_ROOT_HOST=%
    networks:
      - guacamole
    labels:
      - traefik.enable=false

  mysql-init:
    container_name: guacamole-mysql-init
    image: lowet84/mysql-guacamole-init
    build: init/
    volumes:
     - ${SETTINGS_PATH}/guacamole:/data
    environment:
      PASSWORD: gurkburk
    networks:
      - guacamole
    labels:
      - traefik.enable=false

  guacd:
    container_name: guacd
    image: glyptodon/guacd
    restart: always
    networks:
      - guacamole
    labels:
      - traefik.enable=false

  guacamole:
    container_name: guacamole
    image: guacamole
    build: guacamole/
    restart: always
    networks:
      - guacamole
      - core
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
      MYSQL_HOSTNAME: guacamole-mysql
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:guacamole.${SERVER_DOMAIN}
      - traefik.docker.network=core

networks:
  guacamole:
  core:
    external: true
