version: '3'
services:
  gogs:
    container_name: gogs
    image: gogs/gogs
    restart: always
    volumes:
      - ${SETTINGS_PATH}/gogs:/data
      - ${BACKUP_PATH}:/backup
    networks:
      - core
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:gogs.${SERVER_DOMAIN}

  gogs-backup:
    container_name: gogs-backup
    image: gogs-backup
    build: backup
    restart: always
    networks:
      - core
    volumes:
      - ${SETTINGS_PATH}/gogs/backup:/config
      - ${BACKUP_PATH}:/backup
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  core:
    external: true
