version: '3'
services:
  storybook:
    container_name: storybook
    image: docker.fredriklowenhamn.se/storybook-docs
    restart: always
    networks:
      - core
    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:storybook.${SERVER_DOMAIN}

networks:
  core:
    external: true
