version: '3'
services:
  storybook:
    container_name: storybook
    image: docker.fredriklowenhamn.se/storybook-docs
    restart: always
    networks:
      - core
    labels:
      - traefik.port=8043
      - traefik.frontend.rule=Host:storybook.${SERVER_DOMAIN}
      - com.centurylinklabs.watchtower.enable=true

networks:
  core:
    external: true
