# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

# https is the default
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
email = "fredriklowenhamn@gmail.com" #Change this to your email
storage = "/config/acme-public.json"
entryPoint = "https"
onDemand = true

[acme.httpChallenge]
entryPoint = "http"

[file]
watch=true

[backends]
  [backends.oauth2]
    [backends.oauth2.servers.oauth2]
    url = "http://oauth2proxy:4180"

[frontends]
  [frontends.oauth2]
  backend = "oauth2"
  passHostHeader = true
  priority = 1
    [frontends.oauth2.routes.oauth2]
    rule = "HostRegexp:{catchall:.*}"

