version: '3'
services:
  portal:
    container_name: portal
    image: lowet84/traefik-portal
    restart: always
    networks:
      - core
    labels:
      - traefik.port=3000
      - traefik.frontend.rule=Host:portal.${SERVER_DOMAIN}
    environment:
      - TRAEFIK=http://traefik.${SERVER_DOMAIN}

networks:
  core:
    external: true
